---
title:               Not Tom's Blog
tagline:             A place for thoughts
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Tom Brown
twitter:             @nottombrown
github:              nottombrown
email:               tom@joingrouper.com
google_analytics_id: YOUR_GA_ID